name: "docker"

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        default: 'dev'

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
      - name: check version
        id: check-version
        run: |
          if [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            dashversion=$(echo ${{ inputs.version }} | sed -e 's/\./_/g')
          elif [ "${{ inputs.version }}" == "dev" ]; then
            dashversion="${{ inputs.version }}"
          else
            echo "version must be of the form \"^[0-9]+\.[0-9]+\.[0-9]+$\" or \"dev\"."
            exit 1
          fi
          echo "dashversion=$dashversion" >> "$GITHUB_OUTPUT"
      - name: usetag
        env:
          dashversion: ${{ steps.check-version.outputs.dashversion }}
        run: |
          echo $dashversion
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: tsteven4
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:tools/archive_images"
          file: "Dockerfile_gpsbabel_${{ steps.check-version.outputs.dashversion}}"
          push: false
          tags: tsteven4/gpsbabel:${{ inputs.version }}
